### ISSUE TITLE
Hotkeys stop successfully working after selecting last opened EVE client

### ISSUE THREAD

**Issue by Groot2C** [EveOPlus/eve-o-preview#12]
https://github.com/Phrynohyas/eve-o-preview/issues/204

Exact same issue as described in the previous EVE-O github. Has anyone found a solution yet? 

Basically what happens is after I select my last opened EVE client, I can no longer use hotkey's to switch to any other client until I either click off my eve window or manually select a different client from the thumbnails.

**Comment by Groot2C** [comment]
Funnily enough -- I just found a workaround of using the "minimize inactive eve clients" where it will let you "break out" and continue to cycle once the "stuck" account is minimized.

**Comment by feyyd** [comment]
I actually can't reproduce this when I tried.  Can you provide your json settings file so I can attempt to reproduce with same settings?  Also, how many accounts were you using?

**Comment by EvictionCo** [comment]
Having this issue myself, 4 clients. JSON:
```json
{
  "ConfigVersion": 1,
  "CycleGroup1ForwardHotkeys": [
    "F15",
    "Control+F15"
  ],
  "CycleGroup1BackwardHotkeys": [
    "F14",
    "Control+F14"
  ],
  "CycleGroup1ClientsOrder": {
    "EVE - Jimmy Eviction": 4,
    "EVE - Edward Eviction": 3,
    "EVE - Marcus Eviction": 2,
    "EVE - Harold Eviction": 1
  },
  "CycleGroup2ForwardHotkeys": [
    "F16",
    "Control+F16"
  ],
  "CycleGroup2BackwardHotkeys": [
    "F15",
    "Control+F15"
  ],
  "CycleGroup2ClientsOrder": {
    "EVE - Example Logi Toon 1": 1,
    "EVE - Example Scout Toon 2": 2,
    "EVE - Example Tackle Toon 3": 3
  },
  "PerClientActiveClientHighlightColor": {
    "EVE - Example Toon 1": "Red",
    "EVE - Example Toon 2": "Green"
  },
  "MinimizeToTray": true,
  "ThumbnailRefreshPeriod": 500,
  "CompatibilityMode": false,
  "ThumbnailsOpacity": 0.5,
  "EnableClientLayoutTracking": false,
  "HideActiveClientThumbnail": false,
  "MinimizeInactiveClients": false,
  "ShowThumbnailsAlwaysOnTop": true,
  "EnablePerClientThumbnailLayouts": false,
  "HideThumbnailsOnLostFocus": false,
  "HideThumbnailsDelay": 2,
  "ThumbnailSize": "384, 216",
  "ThumbnailMaximumSize": "960, 540",
  "ThumbnailMinimumSize": "192, 108",
  "EnableThumbnailSnap": true,
  "EnableThumbnailZoom": false,
  "ThumbnailZoomFactor": 2,
  "ThumbnailZoomAnchor": 0,
  "ShowThumbnailOverlays": true,
  "ShowThumbnailFrames": false,
  "EnableActiveClientHighlight": true,
  "ActiveClientHighlightColor": "GreenYellow",
  "ActiveClientHighlightThickness": 3,
  "LoginThumbnailLocation": "5, 5",
  "PerClientLayout": {},
  "FlatLayout": {
    "EVE - Jimmy Eviction": "2490, 3",
    "EVE - Edward Eviction": "2104, 3",
    "EVE - Marcus Eviction": "1727, 5",
    "EVE - Harold Eviction": "1343, 5"
  },
  "ClientLayout": {},
  "ClientHotkey": {},
  "DisableThumbnail": {},
  "PriorityClients": []
}
```

Windows 10 latest, EVE-O Preview 6.0.0.3, client windows are Fixed Window.

**Comment by Evolution0** [comment]
Interestingly enough when it does this its not like it refuses to cycle, it cycles then pops back to the last client as if whatever code is attached to the hotkey functionality is _switching_ clients temporarily, but can't _set_ whatever value contains the active client so it gets switched back the next process tick.

**Comment by tekeve** [comment]
I found this is an issue when Overwolf is running - exiting Overwolf in the system tray resolved.

**Comment by tylort69** [comment]
> I found this is an issue when Overwolf is running - exiting Overwolf in the system tray resolved.

I can confirm that this solved the issue for me.

**Comment by Zerbia01** [comment]
thank you so much, experienced this bug for a month bwefore i unsubbed my other accounts, made my evenings hell, even tried using ISBoxer which didnt solve the problem. overwolf piece of shit malware.
